import './global.css';
import HeaderSection from "@meetfaq/marketing/components/HeaderSection";
import {Inter} from "next/font/google";
import Footer from "@meetfaq/marketing/components/FooterSection";

export const revalidate = 3600;

export const metadata = {
  title: 'Welcome to marketing',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({ subsets: ['latin'] })

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {stargazers_count} = await (await fetch('https://api.github.com/repos/github-20k/meetqa', {cache: 'force-cache', next: {revalidate}})).json();
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderSection stars={stargazers_count} />
        <div className="min-h-screen flex flex-col gap-[40px]">
          <main className="flex-1 flex flex-col">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
